### ISSUE TITLE
[Feature] Add feature to generate yaml config from existing build

### ISSUE THREAD

**Issue by amanshaw4511** [amanshaw4511/jenkinsctl#1]
User will run command like this
```jenkinsctl config <job_name> <build_no>```

eg.
```jenkinsctl config myjob 2```

OUTPUT
```
job: myjob
params:
    param1: hello
    param2: 3
    param3: true
```
